specVersion: 1.0.0
version: 1.0.0
description: Indexer for RMRK based on SubQuery Starter
repository: ""
runner:
  node:
    name: '@subql/node'
    version: ">1.0.0"
  query:
    name: '@subql/query'
    version: ">1.0.0"
schema:
  file: ./schema.graphql
network:
  # endpoint: wss://node-6885049485545332736.jm.onfinality.io/ws?apikey=652fed48-a419-4272-bd8a-f020d0b7a740
  # endpoint: wss://pub.elara.patract.io/kusama
  endpoint: wss://kusama.api.onfinality.io/public-ws
  # endpoint: wss://kusama-rpc.polkadot.io
  dictionary: https://api.subquery.network/sq/subquery/dictionary-kusama
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
definitions:
  mapping: &mymapping
    file: ./dist/index.js
    handlers:
      - handler: handleBlock
        kind: substrate/BlockHandler
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: utility
          method: batchAll
          success: true
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: utility
          method: batch
          success: true
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: system
          method: remark
          success: true
dataSources:
  - name: main
    kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 4892957 #6802210 #4892957
    mapping: *mymapping # can reuse or change
  - name: westendRuntime
    kind: substrate/Runtime
    filter:
      specName: westend
    startBlock: 7161214
    mapping: *mymapping # can reuse or change