specVersion: 0.0.1
description: Indexer for RMRK based on SubQuery Starter
repository: ""
schema: ./schema.graphql
network:
  endpoint: wss://pub.elara.patract.io/kusama
  # endpoint: wss://kusama.api.onfinality.io/public-ws
  # endpoint: wss://kusama-rpc.polkadot.io
  dictionary: https://api.subquery.network/sq/subquery/dictionary-kusama
definitions:
  mapping: &mymapping
    handlers:
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: utility
          method: batchAll
          success: true
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: utility
          method: batch
          success: true
      - handler: handleRemark
        kind: substrate/CallHandler
        filter:
          module: system
          method: remark
          success: true
dataSources:
  - name: main
    kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 9807000  #6802210 #4892957
    mapping: *mymapping # can reuse or change
  - name: westendRuntime
    kind: substrate/Runtime
    filter:
      specName: westend
    startBlock: 7161214
    mapping: *mymapping # can reuse or change
